risky: false

enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow

disabled:
  - align_double_arrow
  - concat_without_spaces
  - phpdoc_indent
  - phpdoc_params

finder:
  exclude:
    - "tests"
  name:
    - "*.php"

