language: php

php:
  - 7.0
  - 7.1

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:^1.3"
  - composer install

  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - php coveralls.phar --version


before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

  - mkdir -p build/logs
  - ls -al

script:
    - php vendor/bin/phpunit -c phpunit.xml.dist
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml


after_script:
  - travis_retry php coveralls.phar -v

branches:
  only: master

cache:
  directories:
  - vendor
  - $HOME/.cache/composer